# Setup
title:               Sahil Karawade
description:         Interested in Alebraic Geometry more specifically Arithmetic Geometry and Moduli spaces
url:                 https://sahil-karawade.github.io/Sahil/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Sahil Karawade
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
